local Plug = vim.fn["plug#"]

vim.call("plug#begin")

Plug("neovim/nvim-lspconfig")
Plug("mileszs/ack.vim")
Plug("editorconfig/editorconfig-vim")
Plug("vim-scripts/matchit.zip")
Plug("tomtom/tlib_vim")
Plug("edkolev/tmuxline.vim")
Plug("tpope/vim-abolish")
Plug("MarcWeber/vim-addon-mw-utils")
Plug("vim-airline/vim-airline")
Plug("vim-airline/vim-airline-themes")
Plug("Townk/vim-autoclose")
Plug("tpope/vim-commentary")
Plug("tpope/vim-eunuch")
Plug("tpope/vim-fugitive")
Plug("tpope/vim-markdown")
Plug("tpope/vim-rails")
Plug("tpope/vim-repeat")
Plug("tpope/vim-rhubarb")
Plug("ecomba/vim-ruby-refactoring")
Plug("honza/vim-snippets")
Plug("dcampos/nvim-snippy")
Plug("quangnguyen30192/cmp-nvim-tags")
Plug("dcampos/cmp-snippy")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/nvim-cmp")
Plug("tpope/vim-surround")
Plug("skalnik/vim-vroom")
Plug("dense-analysis/ale")
Plug("junegunn/fzf", {["do"] = function() vim.fn["fzf#install"]() end})
Plug("junegunn/fzf.vim")
Plug("sheerun/vim-polyglot")
Plug("sainnhe/sonokai")
Plug("nvim-treesitter/nvim-treesitter", {["do"] = vim.fn.TSUpdate})

vim.call("plug#end")
