require("plugins.ale")
require("plugins.fzf")
require("plugins.nvim-cmp")
require("plugins.nvim-lspconfig")
require("plugins.nvim-snippy")
require("plugins.nvim-treesitter")
require("plugins.vim-vroom")
