#!/bin/bash

pcomux() {
  if [ -z "$(tmux list-sessions 2>/dev/null | grep pco)" ]; then
    start_pcomux
  fi

  join_pcomux
}

start_pcomux() {
  tmux new -d -s pco

  # Accounts
  tmux rename-window "accounts"
  tmux send-keys "cd ~/Code/accounts" C-m

  # API
  tmux new-window -t pco -n "api"
  tmux select-window -t "api"
  tmux send-keys "cd ~/Code/api" C-m

  # Check-Ins
  tmux new-window -t pco -n "check-ins"
  tmux select-window -t "check-ins"
  tmux send-keys "cd ~/Code/check-ins" C-m

  # Church Center
  tmux new-window -t pco -n "church-center"
  tmux select-window -t "church-center"
  tmux send-keys "cd ~/Code/church-center" C-m

  # People
  tmux new-window -t pco -n "people"
  tmux select-window -t "people"
  tmux send-keys "cd ~/Code/people" C-m

  # Registrations
  tmux new-window -t pco -n "registrations"
  tmux select-window -t "registrations"
  tmux send-keys "cd ~/Code/registrations" C-m

  # Resources
  tmux new-window -t pco -n "resources"
  tmux select-window -t "resources"
  tmux send-keys "cd ~/Code/resources" C-m

  # Services
  tmux new-window -t pco -n "services"
  tmux select-window -t "services"
  tmux send-keys "cd ~/Code/services" C-m

  # Account Center Integration
  tmux new-window -t pco -n "aci"
  tmux select-window -t "aci"
  tmux send-keys "cd ~/Code/account_center_integration" C-m

  # Church Center Integration
  tmux new-window -t pco -n "cci"
  tmux select-window -t "cci"
  tmux send-keys "cd ~/Code/church-center-integration" C-m

  tmux select-window -t "people"
}

join_pcomux() {
  tmux attach -t pco
}
