#!/bin/sh
set -e
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf .git/tags.$$ --exclude=.git --exclude=node_modules --exclude=tmp --exclude=public --languages=-markdown,rspec,sql
mv .git/tags.$$ .git/tags
